version: '3.8'
services:
  dynamoDB-test:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: amazon/dynamodb-local
    container_name: dynamoDB-test
    ports:
      - '8000:8000'
    volumes:
      - '../../docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=123
      - AWS_DEFAULT_REGION=eu-west-1
